[tool.poetry]
name = "{{ $base }}"
version = "0.1.0"
description = "{{ $description }}"
authors = []

[tool.poetry.dependencies]
python = "^3.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
